# Generated by Django 4.1 on 2022-08-30 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentDate', models.DateTimeField(default=datetime.datetime(2022, 8, 29, 22, 29, 34, 44764))),
                ('nome', models.CharField(default='SEM NOME', max_length=200)),
                ('turma', models.CharField(choices=[('M1A', 'M1A'), ('M1B', 'M1B'), ('M2A', 'M2A'), ('M2B', 'M2B')], max_length=4)),
                ('flor', models.CharField(choices=[('tulipa', 'Tulipa'), ('rosa', 'Rosa')], max_length=10)),
            ],
        ),
    ]
