# Generated by Django 4.1 on 2022-08-30 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='currentDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 22, 51, 49, 854752)),
        ),
    ]
