# Generated by Django 4.1.1 on 2022-09-06 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_vote_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='currentDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 11, 58, 55, 557466)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='flor',
            field=models.CharField(choices=[('Tulipa', 'Tulipa'), ('Tosa', 'Rosa')], max_length=10),
        ),
    ]
