# Generated by Django 4.1 on 2022-09-14 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_vote_currentdate_alter_vote_flor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='currentDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 22, 10, 28, 649380)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='flor',
            field=models.CharField(choices=[('Tulipa', 'Tulipa'), ('Rosa', 'Rosa'), ('Margarida', 'Margarida')], max_length=10),
        ),
    ]
