# Generated by Django 4.1 on 2022-09-14 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_alter_vote_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='currentDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 22, 18, 57, 294439)),
        ),
    ]
