# Generated by Django 4.1 on 2022-09-14 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_alter_vote_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='currentDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 22, 30, 16, 123709)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='flor',
            field=models.CharField(choices=[('Tulipa', 'Tulipa'), ('Rosa', 'Rosa'), ('Flores do Campo', 'Flores do Campo')], max_length=30),
        ),
    ]
